---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ?Verify fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Set up the repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu stretch stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start Docker on boot

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-{{ ansible_system }}-{{ ansible_users }}
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 'u+x, g+x'

- name: Set periodic Docker prune
  cron:
    name: docker-prune
    job: 'docker system prune -af --filter until=720h'
    minute: '0'
    hour: '1'

- name: Remove useless packages
  apt:
    autoclean: yes

- name: Remove useles dependencies
  apt:
    autoremove: yes